# Generated by Django 3.2.5 on 2021-08-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20210803_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='Наличие SD карты'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_max_volume',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Максимальное объём встраиваемой памяти'),
        ),
    ]
